# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/binwatson/share/zbinbin

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/binwatson/share/zbinbin

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/binwatson/share/zbinbin/CMakeFiles /home/binwatson/share/zbinbin/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/binwatson/share/zbinbin/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named AsyncLogging_test

# Build rule for target.
AsyncLogging_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AsyncLogging_test
.PHONY : AsyncLogging_test

# fast build rule for target.
AsyncLogging_test/fast:
	$(MAKE) -f CMakeFiles/AsyncLogging_test.dir/build.make CMakeFiles/AsyncLogging_test.dir/build
.PHONY : AsyncLogging_test/fast

#=============================================================================
# Target rules for targets named zbinbin

# Build rule for target.
zbinbin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zbinbin
.PHONY : zbinbin

# fast build rule for target.
zbinbin/fast:
	$(MAKE) -f CMakeFiles/zbinbin.dir/build.make CMakeFiles/zbinbin.dir/build
.PHONY : zbinbin/fast

#=============================================================================
# Target rules for targets named log_test

# Build rule for target.
log_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 log_test
.PHONY : log_test

# fast build rule for target.
log_test/fast:
	$(MAKE) -f CMakeFiles/log_test.dir/build.make CMakeFiles/log_test.dir/build
.PHONY : log_test/fast

tests/AsyncLogging_test.o: tests/AsyncLogging_test.cpp.o

.PHONY : tests/AsyncLogging_test.o

# target to build an object file
tests/AsyncLogging_test.cpp.o:
	$(MAKE) -f CMakeFiles/AsyncLogging_test.dir/build.make CMakeFiles/AsyncLogging_test.dir/tests/AsyncLogging_test.cpp.o
.PHONY : tests/AsyncLogging_test.cpp.o

tests/AsyncLogging_test.i: tests/AsyncLogging_test.cpp.i

.PHONY : tests/AsyncLogging_test.i

# target to preprocess a source file
tests/AsyncLogging_test.cpp.i:
	$(MAKE) -f CMakeFiles/AsyncLogging_test.dir/build.make CMakeFiles/AsyncLogging_test.dir/tests/AsyncLogging_test.cpp.i
.PHONY : tests/AsyncLogging_test.cpp.i

tests/AsyncLogging_test.s: tests/AsyncLogging_test.cpp.s

.PHONY : tests/AsyncLogging_test.s

# target to generate assembly for a file
tests/AsyncLogging_test.cpp.s:
	$(MAKE) -f CMakeFiles/AsyncLogging_test.dir/build.make CMakeFiles/AsyncLogging_test.dir/tests/AsyncLogging_test.cpp.s
.PHONY : tests/AsyncLogging_test.cpp.s

tests/log_test.o: tests/log_test.cpp.o

.PHONY : tests/log_test.o

# target to build an object file
tests/log_test.cpp.o:
	$(MAKE) -f CMakeFiles/log_test.dir/build.make CMakeFiles/log_test.dir/tests/log_test.cpp.o
.PHONY : tests/log_test.cpp.o

tests/log_test.i: tests/log_test.cpp.i

.PHONY : tests/log_test.i

# target to preprocess a source file
tests/log_test.cpp.i:
	$(MAKE) -f CMakeFiles/log_test.dir/build.make CMakeFiles/log_test.dir/tests/log_test.cpp.i
.PHONY : tests/log_test.cpp.i

tests/log_test.s: tests/log_test.cpp.s

.PHONY : tests/log_test.s

# target to generate assembly for a file
tests/log_test.cpp.s:
	$(MAKE) -f CMakeFiles/log_test.dir/build.make CMakeFiles/log_test.dir/tests/log_test.cpp.s
.PHONY : tests/log_test.cpp.s

zbinbin/log/AsyncLogging.o: zbinbin/log/AsyncLogging.cpp.o

.PHONY : zbinbin/log/AsyncLogging.o

# target to build an object file
zbinbin/log/AsyncLogging.cpp.o:
	$(MAKE) -f CMakeFiles/zbinbin.dir/build.make CMakeFiles/zbinbin.dir/zbinbin/log/AsyncLogging.cpp.o
.PHONY : zbinbin/log/AsyncLogging.cpp.o

zbinbin/log/AsyncLogging.i: zbinbin/log/AsyncLogging.cpp.i

.PHONY : zbinbin/log/AsyncLogging.i

# target to preprocess a source file
zbinbin/log/AsyncLogging.cpp.i:
	$(MAKE) -f CMakeFiles/zbinbin.dir/build.make CMakeFiles/zbinbin.dir/zbinbin/log/AsyncLogging.cpp.i
.PHONY : zbinbin/log/AsyncLogging.cpp.i

zbinbin/log/AsyncLogging.s: zbinbin/log/AsyncLogging.cpp.s

.PHONY : zbinbin/log/AsyncLogging.s

# target to generate assembly for a file
zbinbin/log/AsyncLogging.cpp.s:
	$(MAKE) -f CMakeFiles/zbinbin.dir/build.make CMakeFiles/zbinbin.dir/zbinbin/log/AsyncLogging.cpp.s
.PHONY : zbinbin/log/AsyncLogging.cpp.s

zbinbin/log/LogStream.o: zbinbin/log/LogStream.cpp.o

.PHONY : zbinbin/log/LogStream.o

# target to build an object file
zbinbin/log/LogStream.cpp.o:
	$(MAKE) -f CMakeFiles/zbinbin.dir/build.make CMakeFiles/zbinbin.dir/zbinbin/log/LogStream.cpp.o
.PHONY : zbinbin/log/LogStream.cpp.o

zbinbin/log/LogStream.i: zbinbin/log/LogStream.cpp.i

.PHONY : zbinbin/log/LogStream.i

# target to preprocess a source file
zbinbin/log/LogStream.cpp.i:
	$(MAKE) -f CMakeFiles/zbinbin.dir/build.make CMakeFiles/zbinbin.dir/zbinbin/log/LogStream.cpp.i
.PHONY : zbinbin/log/LogStream.cpp.i

zbinbin/log/LogStream.s: zbinbin/log/LogStream.cpp.s

.PHONY : zbinbin/log/LogStream.s

# target to generate assembly for a file
zbinbin/log/LogStream.cpp.s:
	$(MAKE) -f CMakeFiles/zbinbin.dir/build.make CMakeFiles/zbinbin.dir/zbinbin/log/LogStream.cpp.s
.PHONY : zbinbin/log/LogStream.cpp.s

zbinbin/log/Logging.o: zbinbin/log/Logging.cpp.o

.PHONY : zbinbin/log/Logging.o

# target to build an object file
zbinbin/log/Logging.cpp.o:
	$(MAKE) -f CMakeFiles/zbinbin.dir/build.make CMakeFiles/zbinbin.dir/zbinbin/log/Logging.cpp.o
.PHONY : zbinbin/log/Logging.cpp.o

zbinbin/log/Logging.i: zbinbin/log/Logging.cpp.i

.PHONY : zbinbin/log/Logging.i

# target to preprocess a source file
zbinbin/log/Logging.cpp.i:
	$(MAKE) -f CMakeFiles/zbinbin.dir/build.make CMakeFiles/zbinbin.dir/zbinbin/log/Logging.cpp.i
.PHONY : zbinbin/log/Logging.cpp.i

zbinbin/log/Logging.s: zbinbin/log/Logging.cpp.s

.PHONY : zbinbin/log/Logging.s

# target to generate assembly for a file
zbinbin/log/Logging.cpp.s:
	$(MAKE) -f CMakeFiles/zbinbin.dir/build.make CMakeFiles/zbinbin.dir/zbinbin/log/Logging.cpp.s
.PHONY : zbinbin/log/Logging.cpp.s

zbinbin/thread/Condition.o: zbinbin/thread/Condition.cpp.o

.PHONY : zbinbin/thread/Condition.o

# target to build an object file
zbinbin/thread/Condition.cpp.o:
	$(MAKE) -f CMakeFiles/zbinbin.dir/build.make CMakeFiles/zbinbin.dir/zbinbin/thread/Condition.cpp.o
.PHONY : zbinbin/thread/Condition.cpp.o

zbinbin/thread/Condition.i: zbinbin/thread/Condition.cpp.i

.PHONY : zbinbin/thread/Condition.i

# target to preprocess a source file
zbinbin/thread/Condition.cpp.i:
	$(MAKE) -f CMakeFiles/zbinbin.dir/build.make CMakeFiles/zbinbin.dir/zbinbin/thread/Condition.cpp.i
.PHONY : zbinbin/thread/Condition.cpp.i

zbinbin/thread/Condition.s: zbinbin/thread/Condition.cpp.s

.PHONY : zbinbin/thread/Condition.s

# target to generate assembly for a file
zbinbin/thread/Condition.cpp.s:
	$(MAKE) -f CMakeFiles/zbinbin.dir/build.make CMakeFiles/zbinbin.dir/zbinbin/thread/Condition.cpp.s
.PHONY : zbinbin/thread/Condition.cpp.s

zbinbin/thread/CountDownLatch.o: zbinbin/thread/CountDownLatch.cpp.o

.PHONY : zbinbin/thread/CountDownLatch.o

# target to build an object file
zbinbin/thread/CountDownLatch.cpp.o:
	$(MAKE) -f CMakeFiles/zbinbin.dir/build.make CMakeFiles/zbinbin.dir/zbinbin/thread/CountDownLatch.cpp.o
.PHONY : zbinbin/thread/CountDownLatch.cpp.o

zbinbin/thread/CountDownLatch.i: zbinbin/thread/CountDownLatch.cpp.i

.PHONY : zbinbin/thread/CountDownLatch.i

# target to preprocess a source file
zbinbin/thread/CountDownLatch.cpp.i:
	$(MAKE) -f CMakeFiles/zbinbin.dir/build.make CMakeFiles/zbinbin.dir/zbinbin/thread/CountDownLatch.cpp.i
.PHONY : zbinbin/thread/CountDownLatch.cpp.i

zbinbin/thread/CountDownLatch.s: zbinbin/thread/CountDownLatch.cpp.s

.PHONY : zbinbin/thread/CountDownLatch.s

# target to generate assembly for a file
zbinbin/thread/CountDownLatch.cpp.s:
	$(MAKE) -f CMakeFiles/zbinbin.dir/build.make CMakeFiles/zbinbin.dir/zbinbin/thread/CountDownLatch.cpp.s
.PHONY : zbinbin/thread/CountDownLatch.cpp.s

zbinbin/thread/CurrentThread.o: zbinbin/thread/CurrentThread.cpp.o

.PHONY : zbinbin/thread/CurrentThread.o

# target to build an object file
zbinbin/thread/CurrentThread.cpp.o:
	$(MAKE) -f CMakeFiles/zbinbin.dir/build.make CMakeFiles/zbinbin.dir/zbinbin/thread/CurrentThread.cpp.o
.PHONY : zbinbin/thread/CurrentThread.cpp.o

zbinbin/thread/CurrentThread.i: zbinbin/thread/CurrentThread.cpp.i

.PHONY : zbinbin/thread/CurrentThread.i

# target to preprocess a source file
zbinbin/thread/CurrentThread.cpp.i:
	$(MAKE) -f CMakeFiles/zbinbin.dir/build.make CMakeFiles/zbinbin.dir/zbinbin/thread/CurrentThread.cpp.i
.PHONY : zbinbin/thread/CurrentThread.cpp.i

zbinbin/thread/CurrentThread.s: zbinbin/thread/CurrentThread.cpp.s

.PHONY : zbinbin/thread/CurrentThread.s

# target to generate assembly for a file
zbinbin/thread/CurrentThread.cpp.s:
	$(MAKE) -f CMakeFiles/zbinbin.dir/build.make CMakeFiles/zbinbin.dir/zbinbin/thread/CurrentThread.cpp.s
.PHONY : zbinbin/thread/CurrentThread.cpp.s

zbinbin/thread/Thread.o: zbinbin/thread/Thread.cpp.o

.PHONY : zbinbin/thread/Thread.o

# target to build an object file
zbinbin/thread/Thread.cpp.o:
	$(MAKE) -f CMakeFiles/zbinbin.dir/build.make CMakeFiles/zbinbin.dir/zbinbin/thread/Thread.cpp.o
.PHONY : zbinbin/thread/Thread.cpp.o

zbinbin/thread/Thread.i: zbinbin/thread/Thread.cpp.i

.PHONY : zbinbin/thread/Thread.i

# target to preprocess a source file
zbinbin/thread/Thread.cpp.i:
	$(MAKE) -f CMakeFiles/zbinbin.dir/build.make CMakeFiles/zbinbin.dir/zbinbin/thread/Thread.cpp.i
.PHONY : zbinbin/thread/Thread.cpp.i

zbinbin/thread/Thread.s: zbinbin/thread/Thread.cpp.s

.PHONY : zbinbin/thread/Thread.s

# target to generate assembly for a file
zbinbin/thread/Thread.cpp.s:
	$(MAKE) -f CMakeFiles/zbinbin.dir/build.make CMakeFiles/zbinbin.dir/zbinbin/thread/Thread.cpp.s
.PHONY : zbinbin/thread/Thread.cpp.s

zbinbin/utility/Timestamp.o: zbinbin/utility/Timestamp.cpp.o

.PHONY : zbinbin/utility/Timestamp.o

# target to build an object file
zbinbin/utility/Timestamp.cpp.o:
	$(MAKE) -f CMakeFiles/zbinbin.dir/build.make CMakeFiles/zbinbin.dir/zbinbin/utility/Timestamp.cpp.o
.PHONY : zbinbin/utility/Timestamp.cpp.o

zbinbin/utility/Timestamp.i: zbinbin/utility/Timestamp.cpp.i

.PHONY : zbinbin/utility/Timestamp.i

# target to preprocess a source file
zbinbin/utility/Timestamp.cpp.i:
	$(MAKE) -f CMakeFiles/zbinbin.dir/build.make CMakeFiles/zbinbin.dir/zbinbin/utility/Timestamp.cpp.i
.PHONY : zbinbin/utility/Timestamp.cpp.i

zbinbin/utility/Timestamp.s: zbinbin/utility/Timestamp.cpp.s

.PHONY : zbinbin/utility/Timestamp.s

# target to generate assembly for a file
zbinbin/utility/Timestamp.cpp.s:
	$(MAKE) -f CMakeFiles/zbinbin.dir/build.make CMakeFiles/zbinbin.dir/zbinbin/utility/Timestamp.cpp.s
.PHONY : zbinbin/utility/Timestamp.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... AsyncLogging_test"
	@echo "... zbinbin"
	@echo "... log_test"
	@echo "... tests/AsyncLogging_test.o"
	@echo "... tests/AsyncLogging_test.i"
	@echo "... tests/AsyncLogging_test.s"
	@echo "... tests/log_test.o"
	@echo "... tests/log_test.i"
	@echo "... tests/log_test.s"
	@echo "... zbinbin/log/AsyncLogging.o"
	@echo "... zbinbin/log/AsyncLogging.i"
	@echo "... zbinbin/log/AsyncLogging.s"
	@echo "... zbinbin/log/LogStream.o"
	@echo "... zbinbin/log/LogStream.i"
	@echo "... zbinbin/log/LogStream.s"
	@echo "... zbinbin/log/Logging.o"
	@echo "... zbinbin/log/Logging.i"
	@echo "... zbinbin/log/Logging.s"
	@echo "... zbinbin/thread/Condition.o"
	@echo "... zbinbin/thread/Condition.i"
	@echo "... zbinbin/thread/Condition.s"
	@echo "... zbinbin/thread/CountDownLatch.o"
	@echo "... zbinbin/thread/CountDownLatch.i"
	@echo "... zbinbin/thread/CountDownLatch.s"
	@echo "... zbinbin/thread/CurrentThread.o"
	@echo "... zbinbin/thread/CurrentThread.i"
	@echo "... zbinbin/thread/CurrentThread.s"
	@echo "... zbinbin/thread/Thread.o"
	@echo "... zbinbin/thread/Thread.i"
	@echo "... zbinbin/thread/Thread.s"
	@echo "... zbinbin/utility/Timestamp.o"
	@echo "... zbinbin/utility/Timestamp.i"
	@echo "... zbinbin/utility/Timestamp.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

